# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "check"

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.build]
command = ["cargo", "build", "--color", "always"]
need_stdout = false

[jobs.build-fast-compile]
command = [
    "cargo", "build",
    "--features", "dynamic_linking",
    "--color", "always"
]
need_stdout = false

[jobs.fmt]
command = ["cargo", "fmt"]
need_stdout = false

[jobs.clippy]
command = [
    "cargo", "clippy",
    "--all-targets",
    "--color", "always",
]
need_stdout = false

[jobs.clippy-fix]
command = [
    "cargo", "clippy",
    "--fix", "--allow-dirty",
    "--allow-staged",
    "--color", "always",
]
need_stdout = false

[jobs.test]
command = [
    "cargo", "test", "--color", "always",
    "--", "--color", "always", # see https://github.com/Canop/bacon/issues/124
]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

# If the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back" # so that we don't open the browser at each change

# You can run your application and have the result displayed in bacon,
# *if* it makes sense for this crate. You can run an example the same
# way. Don't forget the `--color always` part or the errors won't be
# properly parsed.
[jobs.run]
command = [
    "cargo", "run",
    "--color", "always",
    # put launch parameters for your program behind a `--` separator
]
need_stdout = true
allow_warnings = true

[jobs.render_graph]
command = [
    "zsh", "-c", "cargo build --features render_graph && cargo run --color always --features render_graph | dot -Tsvg -o render_graph.svg && /Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome `readlink -f render_graph.svg`"

    # put launch parameters for your program behind a `--` separator
]
need_stdout = true
allow_warnings = true

[jobs.fast-compile]
command = [
    "cargo", "run",
    "--color", "always",
    "--features", "dynamic_linking"
    # put launch parameters for your program behind a `--` separator
]
need_stdout = true
allow_warnings = true

# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal global prefs.toml file instead.
[keybindings]
# alt-m = "job:my-job"
shift-r = "job:fast-compile"
b = "job:build"
f = "job:fmt"
shift-f = "job:clippy-fix"
shift-b = "job:build-fast-compile"
g = "job:render_graph"
