#for wasm targets, allowing the use of `cargo run --target wasm32-unknown-unknown` to run a wasm webserver
# requires that `cargo install wasm-server-runner` is installed.
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
#enables WebGPU support
rustflags = ["--cfg=web_sys_unstable_apis"]

[alias]
rf = "run --features fast_compile"
bf = "build --features fast_compile"
w = "r --target wasm32-unknown-unknown --profile wasm --no-default-features"
bw = "b --target wasm32-unknown-unknown --profile wasm --no-default-features"
