name: coverage

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     config:
    #       - { target: "x86_64-unknown-linux-gnu" }
    #       - { target: "wasm32-unknown-unknown" }

    steps:
      - uses: actions/checkout@v3

      - name: Setup dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libasound2-dev libudev-dev cmake g++ libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev

      - name: Install Rust
        run: |
          rustup override set nightly
          rustup component add llvm-tools-preview --toolchain nightly

      - name: Configure cache
        uses: actions/cache@v3
        with:
          key: coverage-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --workspace --codecov --tests --output-path codecov.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: codecov.json
          fail_ci_if_error: true
