name: coverage

on: [push]
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:latest-slim
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dependencies
        run: apt-get update && apt-get install -y pkg-config libasound2-dev libudev-dev cmake g++
      - name: Generate code coverage
        run: |
          cargo tarpaulin -v --workspace --timeout 120 --out Xml --no-fail-fast --tests

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
