# name: coverage

# on: [push]
# jobs:
#   coverage:
#     name: coverage
#     runs-on: ubuntu-latest
#     container:
#       image: xd009642/tarpaulin:latest-slim
#       options: --security-opt seccomp=unconfined

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Setup dependencies
#         run: apt-get update && apt-get install -y pkg-config libasound2-dev libudev-dev cmake g++ libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev
#       - name: Generate code coverage
#         run: |
#           cargo tarpaulin -v --workspace --timeout 120 --out Xml --no-fail-fast
#         # --tests

#       - name: Upload to codecov.io
#         uses: codecov/codecov-action@v2
#         with:
#           token: ${{secrets.CODECOV_TOKEN}}
#           fail_ci_if_error: true


name: coverage
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 
        uses: actions/checkout@v3
      - name: Install Rust toolchain 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --no-fail-fast
        env:
          RUSTC_BOOTSTRAP: '1'
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - name: Run grcov 
        id: coverage
        uses: rraval/grcov@master

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true

          
      # - name: Coveralls upload
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: ${{ steps.coverage.outputs.report }}